ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.5
    two_d_mode: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    publish_tf: true
    publish_tf_to_map: false
    use_control: false
    odom0: /wheel/odom_raw
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10
    odom0_config: [false, false, false, false, false, false,
                   true,  false, false, false, false, false,
                   false, false, false]
    imu0: /livox/imu_corrected
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 20
    imu0_config: [false, false, false, false, false, false,
                  false, false, false, false, false, true,
                  false, false, false]
