// ROS 2 std_msgs/msg/String source IDL for standalone Fast DDS clients.
// Fast DDS-Gen is invoked with -typeros2 and performs the DDS name mangling.
module std_msgs
{
    module msg
    {
        struct _String
        {
            string data;
        };
    };
};
