"""Run the primitive patrol robot in Isaac Sim with ROS 2 control."""

# Isaac extensions must be imported only after SimulationApp is constructed.
# ruff: noqa: E402

from __future__ import annotations

import argparse
import math
import os
import signal
import sys
import tempfile
import time
import traceback
from pathlib import Path

from isaacsim import SimulationApp


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--gui", action="store_true", help="Show the Isaac Sim window.")
    parser.add_argument(
        "--start-paused",
        action="store_true",
        help="Open the stage paused; use the Isaac Sim Play button to start physics.",
    )
    parser.add_argument(
        "--demo",
        action="store_true",
        help="Drive a repeating forward-and-turn pattern.",
    )
    parser.add_argument(
        "--test-seconds",
        type=float,
        default=0.0,
        help="Stop automatically after this many simulated seconds.",
    )
    parser.add_argument("--cmd-vel-topic", default="/cmd_vel")
    parser.add_argument(
        "--command-timeout",
        type=float,
        default=0.6,
        help="Brake if cmd_vel is silent for this many wall-clock seconds.",
    )
    parser.add_argument("--odom-topic", default="/odom")
    parser.add_argument(
        "--lidar-usd-path",
        type=Path,
        default=(Path(value) if (value := os.environ.get("PATROL_ISAAC_LIDAR_USD_PATH")) else None),
        help="Use a local RTX lidar USD asset instead of resolving it from Nucleus.",
    )
    parser.add_argument(
        "--realtime-factor",
        type=float,
        default=1.0,
        help="Maximum simulated seconds per wall second; use 0 for unthrottled.",
    )
    parser.add_argument(
        "--urdf-path",
        type=Path,
        required=True,
        help="Expanded URDF generated by the ROS environment.",
    )
    args, kit_args = parser.parse_known_args()
    # SimulationApp forwards sys.argv to Kit. Remove this script's options so
    # Kit does not interpret --test-seconds as its own shutdown timer.
    sys.argv = [sys.argv[0], *kit_args]
    return args


ARGS = _parse_args()
SIMULATION_APP = SimulationApp({"headless": not ARGS.gui})

import isaacsim.core.experimental.utils.app as app_utils
import isaacsim.core.experimental.utils.stage as stage_utils
import numpy as np
from omni.physx import get_physx_scene_query_interface
import rclpy
from geometry_msgs.msg import TransformStamped, Twist
from nav_msgs.msg import Odometry
from pxr import Gf, PhysxSchema, Usd, UsdGeom, UsdLux, UsdPhysics, UsdShade, Vt
from rclpy.node import Node
from rclpy.signals import SignalHandlerOptions
from rosgraph_msgs.msg import Clock
from sensor_msgs.msg import JointState, PointCloud2
from sensor_msgs_py import point_cloud2
from std_msgs.msg import Header
from tf2_msgs.msg import TFMessage

from isaacsim.asset.importer.urdf.impl import URDFImporter, URDFImporterConfig
from isaacsim.core.simulation_manager import SimulationManager
from isaacsim.robot.experimental.wheeled_robots.controllers import (
    AckermannController,
)
from isaacsim.robot.experimental.wheeled_robots.robots import WheeledRobot
from isaacsim.sensors.experimental.rtx import (
    Lidar,
    LidarSensor,
)


WHEEL_RADIUS = 0.215
WHEEL_BASE = 0.70
TRACK_WIDTH = 0.825
MINIMUM_TURNING_RADIUS = 2.35
MAX_STEERING_ANGLE = math.atan(WHEEL_BASE / MINIMUM_TURNING_RADIUS)
MAX_LINEAR_SPEED = 20.0 / 3.6
PHYSICS_DT = 1.0 / 60.0
REAR_WHEEL_MAX_EFFORT = 120.0
STEERING_MAX_EFFORT = 250.0
REAR_WHEEL_DRIVE_DAMPING = 1000.0
STEERING_DRIVE_STIFFNESS = 5000.0
STEERING_DRIVE_DAMPING = 200.0
TIRE_STATIC_FRICTION = 0.9
TIRE_DYNAMIC_FRICTION = 0.8
MID360_POSITION = np.array([0.40, 0.0, 1.50])
MID360_PATTERN_PATH = Path(__file__).with_name("mid360_pattern.npz")
MID360_RAYS_PER_FRAME = 1_000
ISAAC_ROBOT_PATH = "/World/PatrolRobot"
ISAAC_BASE_LINK_PATH = "/World/PatrolRobot/Geometry/base_footprint"
STEERING_DOF_NAMES = [
    "front_left_steering_joint",
    "front_right_steering_joint",
]
FRONT_WHEEL_DOF_NAMES = [
    "front_left_wheel_joint",
    "front_right_wheel_joint",
]
REAR_WHEEL_DOF_NAMES = [
    "rear_left_wheel_joint",
    "rear_right_wheel_joint",
]
JOINT_STATE_NAMES = [
    *STEERING_DOF_NAMES,
    *FRONT_WHEEL_DOF_NAMES,
    *REAR_WHEEL_DOF_NAMES,
]
IMPORTED_WHEEL_COLLIDER_PATHS = [
    f"{ISAAC_BASE_LINK_PATH}/front_left_steering_link/front_left_wheel_link/cylinder_1",
    f"{ISAAC_BASE_LINK_PATH}/front_right_steering_link/front_right_wheel_link/cylinder_1",
    f"{ISAAC_BASE_LINK_PATH}/rear_left_wheel_link/cylinder_1",
    f"{ISAAC_BASE_LINK_PATH}/rear_right_wheel_link/cylinder_1",
]
ISAAC_WHEEL_COLLIDER_PATHS = [
    f"{path.rsplit('/', 1)[0]}/isaac_sphere_collider"
    for path in IMPORTED_WHEEL_COLLIDER_PATHS
]


def _import_robot(urdf_path: Path, output_dir: Path) -> Path:
    config = URDFImporterConfig(
        urdf_path=str(urdf_path),
        usd_path=str(output_dir),
        merge_fixed_joints=True,
        fix_base=False,
        joint_drive_type="force",
        joint_target_type={
            "front_left_steering_joint": "position",
            "front_right_steering_joint": "position",
            "front_left_wheel_joint": "none",
            "front_right_wheel_joint": "none",
            "rear_left_wheel_joint": "velocity",
            "rear_right_wheel_joint": "velocity",
        },
        override_joint_stiffness={
            "front_left_steering_joint": 5000.0,
            "front_right_steering_joint": 5000.0,
            "front_left_wheel_joint": 0.0,
            "front_right_wheel_joint": 0.0,
            "rear_left_wheel_joint": 0.0,
            "rear_right_wheel_joint": 0.0,
        },
        override_joint_damping={
            "front_left_steering_joint": 200.0,
            "front_right_steering_joint": 200.0,
            # A target type of "none" must have no drive gains.  Leaving a
            # small damping here creates a zero-velocity drive on the passive
            # front wheels and makes their ground contacts chatter.
            "front_left_wheel_joint": 0.0,
            "front_right_wheel_joint": 0.0,
            # Velocity-drive damping acts as the rear motor's proportional
            # torque gain. A value of 10 cannot move the 100+ kg articulation
            # reliably and mostly lets the tire contacts chatter in place.
            "rear_left_wheel_joint": 100.0,
            "rear_right_wheel_joint": 100.0,
        },
        # convert_joints_attributes() runs after apply_joint_drives() and
        # replaces these per-joint gains with the raw URDF dynamics values.
        # Keep it disabled and author the required PhysX limits explicitly
        # after the articulation tensor view has been initialized.
        run_multi_physics_conversion=False,
        run_asset_transformer=False,
    )
    usd_path = URDFImporter(config).import_urdf()
    if not usd_path:
        raise RuntimeError("Isaac Sim URDF importer did not return a USD path")
    return Path(usd_path)


def _add_static_box(
    stage,
    path: str,
    size: tuple[float, float, float],
    position: tuple[float, float, float],
    color: tuple[float, float, float],
    yaw: float = 0.0,
) -> None:
    cube = UsdGeom.Cube.Define(stage, path)
    cube.GetSizeAttr().Set(1.0)
    cube.GetDisplayColorAttr().Set([Gf.Vec3f(*color)])
    xform = UsdGeom.Xformable(cube)
    xform.AddTranslateOp().Set(Gf.Vec3d(*position))
    if yaw:
        xform.AddRotateZOp().Set(math.degrees(yaw))
    xform.AddScaleOp().Set(Gf.Vec3f(*size))
    UsdPhysics.CollisionAPI.Apply(cube.GetPrim())


def _add_static_cylinder(
    stage,
    path: str,
    radius: float,
    height: float,
    position: tuple[float, float, float],
    color: tuple[float, float, float],
) -> None:
    cylinder = UsdGeom.Cylinder.Define(stage, path)
    cylinder.CreateRadiusAttr(radius)
    cylinder.CreateHeightAttr(height)
    cylinder.CreateAxisAttr("Z")
    cylinder.GetDisplayColorAttr().Set([Gf.Vec3f(*color)])
    UsdGeom.Xformable(cylinder).AddTranslateOp().Set(Gf.Vec3d(*position))
    UsdPhysics.CollisionAPI.Apply(cylinder.GetPrim())


def _configure_wheel_colliders(stage) -> None:
    """Replace faceted cylinder contacts with stable Isaac wheel contacts.

    PhysX cooks URDF cylinders as convex geometry.  A heavy chassis resting on
    those facets can continually tip between contact points.  NVIDIA's sample
    Ackermann asset likewise uses a bounding-sphere approximation for wheels.
    Keep the cylinder visuals, but use analytic spheres for Isaac collisions.
    """
    for imported_path, sphere_path in zip(
        IMPORTED_WHEEL_COLLIDER_PATHS,
        ISAAC_WHEEL_COLLIDER_PATHS,
        strict=True,
    ):
        imported_prim = stage.GetPrimAtPath(imported_path)
        if not imported_prim.IsValid():
            raise RuntimeError(f"Imported wheel collider not found: {imported_path}")
        UsdPhysics.CollisionAPI(imported_prim).CreateCollisionEnabledAttr(False)

        sphere = UsdGeom.Sphere.Define(stage, sphere_path)
        sphere.CreateRadiusAttr(WHEEL_RADIUS)
        sphere.CreateVisibilityAttr(UsdGeom.Tokens.invisible)
        UsdPhysics.CollisionAPI.Apply(sphere.GetPrim())


def _bind_tire_physics_material(stage) -> None:
    """Apply deterministic rubber contact properties to wheels and ground."""
    material = UsdShade.Material.Define(stage, "/World/PhysicsMaterials/Tire")
    material_api = UsdPhysics.MaterialAPI.Apply(material.GetPrim())
    material_api.CreateStaticFrictionAttr(TIRE_STATIC_FRICTION)
    material_api.CreateDynamicFrictionAttr(TIRE_DYNAMIC_FRICTION)
    # A heavy, unsuspended AGV tire must not bounce on initial contact.
    material_api.CreateRestitutionAttr(0.0)

    for path in ["/World/Ground", *ISAAC_WHEEL_COLLIDER_PATHS]:
        prim = stage.GetPrimAtPath(path)
        if not prim.IsValid():
            raise RuntimeError(f"Physics collider not found for material binding: {path}")
        UsdShade.MaterialBindingAPI.Apply(prim).Bind(
            material,
            bindingStrength=UsdShade.Tokens.strongerThanDescendants,
            materialPurpose="physics",
        )


def _build_scene(robot_usd: Path) -> WheeledRobot:
    stage = stage_utils.create_new_stage()
    stage_utils.set_stage_up_axis("Z")
    stage_utils.set_stage_units(meters_per_unit=1.0)

    world = UsdGeom.Xform.Define(stage, "/World")
    stage.SetDefaultPrim(world.GetPrim())

    _add_static_box(
        stage,
        "/World/Ground",
        (36.0, 32.0, 0.10),
        (0.0, 0.0, -0.05),
        (0.30, 0.34, 0.40),
    )
    _add_static_box(
        stage,
        "/World/InspectionBox",
        (0.8, 0.8, 2.2),
        (6.0, 4.0, 1.1),
        (0.85, 0.30, 0.12),
    )
    _add_static_cylinder(
        stage,
        "/World/InspectionTank",
        0.45,
        2.4,
        (-4.0, 5.0, 1.2),
        (0.18, 0.65, 0.35),
    )
    wall_color = (0.72, 0.75, 0.80)
    _add_static_box(
        stage,
        "/World/NorthWall",
        (28.0, 0.15, 2.5),
        (0.0, 12.0, 1.25),
        wall_color,
    )
    _add_static_box(
        stage,
        "/World/SouthWall",
        (28.0, 0.15, 2.5),
        (0.0, -12.0, 1.25),
        wall_color,
    )
    _add_static_box(
        stage,
        "/World/EastWall",
        (0.15, 24.0, 2.5),
        (14.0, 0.0, 1.25),
        wall_color,
    )
    _add_static_box(
        stage,
        "/World/WestWall",
        (0.15, 24.0, 2.5),
        (-14.0, 0.0, 1.25),
        wall_color,
    )
    corridor_color = (0.24, 0.50, 0.84)
    _add_static_box(
        stage,
        "/World/NorthCorridorWall",
        (9.0, 0.18, 2.2),
        (4.0, 7.0, 1.1),
        corridor_color,
    )
    _add_static_box(
        stage,
        "/World/WestCorridorWall",
        (0.18, 7.0, 2.2),
        (-7.0, -2.0, 1.1),
        corridor_color,
    )
    _add_static_box(
        stage,
        "/World/EastCorridorWall",
        (0.18, 7.0, 2.2),
        (8.0, 3.0, 1.1),
        corridor_color,
    )
    _add_static_box(
        stage,
        "/World/SouthCorridorWall",
        (8.0, 0.18, 2.2),
        (2.0, -6.5, 1.1),
        corridor_color,
    )
    _add_static_cylinder(
        stage,
        "/World/CentralTank",
        0.60,
        2.5,
        (1.0, -1.0, 1.25),
        (0.55, 0.32, 0.75),
    )
    _add_static_box(
        stage,
        "/World/PalletStack",
        (1.2, 0.9, 2.0),
        (8.0, -5.0, 1.0),
        (0.78, 0.52, 0.20),
        yaw=0.25,
    )
    _add_static_box(
        stage,
        "/World/LowCrate",
        (0.8, 1.2, 1.8),
        (-2.0, -7.0, 0.9),
        (0.82, 0.72, 0.16),
        yaw=-0.2,
    )

    light = UsdLux.DistantLight.Define(stage, "/World/Sun")
    light.CreateIntensityAttr(1800.0)
    light.CreateAngleAttr(0.5)
    UsdGeom.Xformable(light).AddRotateXYZOp().Set(Gf.Vec3f(35.0, -25.0, 20.0))

    robot = WheeledRobot(
        paths=ISAAC_ROBOT_PATH,
        wheel_dof_names=REAR_WHEEL_DOF_NAMES,
        usd_path=str(robot_usd),
        # The wheel radius and joint origins place the tire bottoms at z=0.
        # A 2 cm drop injects enough energy into this unsuspended 180 kg model
        # to excite all four wheel contacts before ROS control even starts.
        positions=[-10.5, -8.5, 0.001],
    )
    _configure_wheel_colliders(stage)
    _bind_tire_physics_material(stage)
    return robot


def _mid360_attributes() -> dict[str, object]:
    """Build an RTX profile from Livox's published scan pattern."""
    if not MID360_PATTERN_PATH.is_file():
        raise FileNotFoundError(
            f"MID-360 scan pattern not found: {MID360_PATTERN_PATH}"
        )
    with np.load(MID360_PATTERN_PATH) as pattern_file:
        pattern = np.asarray(
            pattern_file["azimuth_elevation_deg"], dtype=np.float32
        )
    if pattern.shape != (4, 20_000, 2):
        raise ValueError(
            "MID-360 scan pattern must have shape (4, 20000, 2), got "
            f"{pattern.shape}"
        )
    # The Isaac GMO path accepts at most 1,024 emitter/channel IDs. Uniformly
    # retain every twentieth official sample so trajectory and FOV stay intact.
    pattern = pattern[:, ::20]

    # Use one official 0.1 s window as the emitter state. Multiple states make
    # Isaac Sim 6 select its non-working multi-tick ROS point-cloud path.
    attributes: dict[str, object] = {
        "omni:sensor:modelName": "Livox_MID360_Approximation",
        "omni:sensor:Core:scanType": "SOLID_STATE",
        "omni:sensor:Core:intensityProcessing": "NORMALIZATION",
        "omni:sensor:Core:rayType": "IDEALIZED",
        "omni:sensor:Core:nearRangeM": 0.10,
        "omni:sensor:Core:farRangeM": 70.0,
        "omni:sensor:Core:rangeCount": 1,
        "omni:sensor:Core:rangesMinM": Vt.FloatArray([0.10]),
        "omni:sensor:Core:rangesMaxM": Vt.FloatArray([70.0]),
        "omni:sensor:Core:rangeResolutionM": 0.001,
        "omni:sensor:Core:rangeAccuracyM": 0.02,
        "omni:sensor:Core:pulseTimeNs": 5,
        "omni:sensor:Core:maxReturns": 1,
        "omni:sensor:Core:scanRateBaseHz": 10,
        "omni:sensor:Core:patternFiringRateHz": 10,
        # Use Isaac's supported complete-scan mode for a custom solid-state
        # profile; its multi-tick path does not yield valid returns here.
        "omni:sensor:Core:instantLidar": True,
        "omni:sensor:Core:numberOfEmitters": MID360_RAYS_PER_FRAME,
        # RTX allocates one calibration channel per retained emitter ray.
        "omni:sensor:Core:numberOfChannels": MID360_RAYS_PER_FRAME,
        "omni:sensor:Core:numLines": 4,
        "omni:sensor:Core:numRaysPerLine": Vt.UIntArray([250] * 4),
        "omni:sensor:Core:azimuthErrorMean": 0.0,
        "omni:sensor:Core:azimuthErrorStd": 0.0,
        "omni:sensor:Core:elevationErrorMean": 0.0,
        "omni:sensor:Core:elevationErrorStd": 0.0,
        "omni:sensor:Core:outputFrameOfReference": "SENSOR",
    }
    # Distribute the retained samples over the real 100 ms frame. Motion BVH
    # is enabled above so moving-platform returns use the corresponding pose.
    fire_times = Vt.UIntArray(
        (np.arange(MID360_RAYS_PER_FRAME) * 100_000).tolist()
    )
    channel_ids = Vt.UIntArray(
        (np.arange(MID360_RAYS_PER_FRAME) + 1).tolist()
    )
    range_ids = Vt.UIntArray([0] * MID360_RAYS_PER_FRAME)
    for state_index, state in enumerate(pattern[:1], start=1):
        prefix = f"omni:sensor:Core:emitterState:s{state_index:03}"
        attributes[f"{prefix}:azimuthDeg"] = Vt.FloatArray(
            state[:, 0].tolist()
        )
        attributes[f"{prefix}:elevationDeg"] = Vt.FloatArray(
            state[:, 1].tolist()
        )
        attributes[f"{prefix}:fireTimeNs"] = fire_times
        attributes[f"{prefix}:channelId"] = channel_ids
        attributes[f"{prefix}:rangeId"] = range_ids
    return attributes


def _create_mid360s_lidar() -> LidarSensor:
    """Create a 10 Hz MID-360 RTX lidar and ROS output."""
    lidar_root_path = f"{ISAAC_BASE_LINK_PATH}/mid360s_lidar"
    if ARGS.lidar_usd_path is not None:
        lidar_usd_path = ARGS.lidar_usd_path.expanduser().resolve()
        if not lidar_usd_path.is_file():
            raise FileNotFoundError(f"RTX lidar USD asset not found: {lidar_usd_path}")
        lidar_path = Lidar._create_from_usd(
            path=lidar_root_path, usd_path=str(lidar_usd_path)
        )
        Lidar._apply_schemas(lidar_path, ["OmniSensorGenericLidarCoreAPI"])
        lidar = Lidar(
            path=lidar_path,
            tick_rate=10.0,
            aux_output_level="FULL",
            attributes={
                "omni:sensor:Core:nearRangeM": 0.10,
                "omni:sensor:Core:farRangeM": 70.0,
                "omni:sensor:Core:outputFrameOfReference": "SENSOR",
            },
        )
    else:
        lidar = Lidar.create(
            path=lidar_root_path,
            tick_rate=10.0,
            # Each official-angle sample set is already a complete frame.
            accumulate_outputs=False,
            aux_output_level="FULL",
            attributes=_mid360_attributes(),
            translations=MID360_POSITION,
        )
    lidar_root = stage_utils.get_current_stage().GetPrimAtPath(lidar_root_path)
    if not lidar_root.IsValid():
        raise RuntimeError(f"Failed to attach RTX lidar at {lidar_root_path}")
    base_prim = stage_utils.get_current_stage().GetPrimAtPath(
        ISAAC_BASE_LINK_PATH
    )
    base_to_world = UsdGeom.Xformable(base_prim).ComputeLocalToWorldTransform(
        Usd.TimeCode.Default()
    )
    lidar_to_world = UsdGeom.Xformable(lidar_root).ComputeLocalToWorldTransform(
        Usd.TimeCode.Default()
    )
    lidar_in_base = base_to_world.GetInverse().Transform(
        lidar_to_world.ExtractTranslation()
    )
    print(
        "PATROL_ISAAC_LIDAR_MOUNT "
        f"base=({lidar_in_base[0]:.3f},{lidar_in_base[1]:.3f},"
        f"{lidar_in_base[2]:.3f})",
        flush=True,
    )
    # Vendor USD assets may contain a nested sensor transform. Preserve the
    # explicit override path for troubleshooting, while the custom MID-360 is
    # already authored directly at the correct base-relative mount position.
    if ARGS.lidar_usd_path is not None:
        lidar_prim = lidar.prims[0]
        lidar_to_world = UsdGeom.Xformable(lidar_prim).ComputeLocalToWorldTransform(
            Usd.TimeCode.Default()
        )
        authored_position = base_to_world.GetInverse().Transform(
            lidar_to_world.ExtractTranslation()
        )
        root_translation = MID360_POSITION - np.asarray(
            authored_position, dtype=float
        )
        UsdGeom.XformCommonAPI(lidar_root).SetTranslate(
            Gf.Vec3d(*root_translation)
        )
    # Isaac Sim 6's LidarSensor runtime test explicitly attaches the generic
    # model output annotator before any writer consumes RTX returns.
    sensor = LidarSensor(lidar, annotators=["generic-model-output"])
    sensor.attach_writer(
        "RtxLidarROS2PublishPointCloud",
        topicName="livox/lidar",
        frameId="lidar_link",
    )
    return sensor


def _bicycle_command(
    linear_x: float, angular_z: float
) -> tuple[float, float, float]:
    """Convert cmd_vel to a bounded bicycle steering angle and realized yaw rate."""
    linear_x = float(np.clip(linear_x, -MAX_LINEAR_SPEED, MAX_LINEAR_SPEED))
    if abs(linear_x) < 1e-4:
        return 0.0, 0.0, 0.0
    steering_angle = math.atan(WHEEL_BASE * angular_z / linear_x)
    steering_angle = float(
        np.clip(steering_angle, -MAX_STEERING_ANGLE, MAX_STEERING_ANGLE)
    )
    realized_angular_z = linear_x * math.tan(steering_angle) / WHEEL_BASE
    return linear_x, steering_angle, realized_angular_z


def _stamp(seconds: float):
    whole_seconds = int(seconds)
    nanoseconds = int((seconds - whole_seconds) * 1e9)
    return whole_seconds, nanoseconds


class IsaacRosInterface(Node):
    """Translate ROS 2 velocity commands and publish Isaac Sim state."""

    def __init__(self) -> None:
        super().__init__("patrol_robot_isaac_sim")
        self.linear_x = 0.0
        self.angular_z = 0.0
        self._last_command_monotonic_ns = 0
        self._odom_origin_xy: np.ndarray | None = None
        self.create_subscription(
            Twist, ARGS.cmd_vel_topic, self._on_twist, 10
        )
        self._odom = self.create_publisher(Odometry, ARGS.odom_topic, 10)
        self._joint_states = self.create_publisher(JointState, "/joint_states", 10)
        self._lidar = self.create_publisher(PointCloud2, "/livox/lidar", 10)
        self._tf = self.create_publisher(TFMessage, "/tf", 10)
        self._clock_publisher = self.create_publisher(Clock, "/clock", 10)
        with np.load(MID360_PATTERN_PATH) as pattern_file:
            pattern = np.asarray(
                pattern_file["azimuth_elevation_deg"][0, ::20],
                dtype=np.float64,
            )
        azimuth = np.deg2rad(pattern[:, 0])
        elevation = np.deg2rad(pattern[:, 1])
        horizontal = np.cos(elevation)
        self._lidar_directions = np.column_stack(
            (
                horizontal * np.cos(azimuth),
                horizontal * np.sin(azimuth),
                np.sin(elevation),
            )
        )
        self._scene_query = get_physx_scene_query_interface()

    def _on_twist(self, message: Twist) -> None:
        self.linear_x = float(message.linear.x)
        self.angular_z = float(message.angular.z)
        self._last_command_monotonic_ns = time.monotonic_ns()

    def demo_command(self, simulation_time: float) -> tuple[float, float]:
        phase = simulation_time % 14.55
        if phase < 4.0:
            return 0.35, 0.0
        return 0.35, 0.149

    def command(self, simulation_time: float) -> tuple[float, float]:
        if ARGS.demo and self._last_command_monotonic_ns == 0:
            return self.demo_command(simulation_time)
        self.command_timeout_brake()
        return self.linear_x, self.angular_z

    def command_timeout_brake(self) -> None:
        """Zero the stored command if it has gone stale (wall-clock timeout)."""
        if (
            self._last_command_monotonic_ns
            and time.monotonic_ns() - self._last_command_monotonic_ns
            > int(ARGS.command_timeout * 1e9)
        ):
            self.linear_x = 0.0
            self.angular_z = 0.0

    def publish_lidar(
        self,
        simulation_time: float,
        base_position: np.ndarray,
        orientation_wxyz: np.ndarray,
    ) -> None:
        """Raycast the official MID-360 directions into the PhysX scene."""
        w, x, y, z = (float(value) for value in orientation_wxyz)
        rotation = np.array(
            [
                [1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)],
                [2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)],
                [2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)],
            ],
            dtype=np.float64,
        )
        origin = np.asarray(base_position, dtype=np.float64) + rotation @ MID360_POSITION
        world_directions = self._lidar_directions @ rotation.T
        ray_origin = Gf.Vec3f(*(float(value) for value in origin))
        points: list[tuple[float, float, float]] = []
        for local_direction, world_direction in zip(
            self._lidar_directions, world_directions, strict=True
        ):
            hit = self._scene_query.raycast_closest(
                ray_origin,
                Gf.Vec3f(*(float(value) for value in world_direction)),
                70.0,
            )
            if not hit or not hit["hit"]:
                continue
            hit_position = np.asarray(hit["position"], dtype=np.float64)
            distance = float(np.linalg.norm(hit_position - origin))
            if distance < 0.10:
                continue
            point = local_direction * distance
            points.append((float(point[0]), float(point[1]), float(point[2])))

        sec, nanosec = _stamp(simulation_time)
        header = Header()
        header.stamp.sec = sec
        header.stamp.nanosec = nanosec
        header.frame_id = "lidar_link"
        self._lidar.publish(point_cloud2.create_cloud_xyz32(header, points))

    def publish_state(
        self,
        simulation_time: float,
        position: np.ndarray,
        orientation_wxyz: np.ndarray,
        joint_positions: np.ndarray,
        linear_x: float,
        angular_z: float,
    ) -> None:
        sec, nanosec = _stamp(simulation_time)
        if self._odom_origin_xy is None:
            self._odom_origin_xy = np.asarray(position[:2], dtype=float).copy()
        odom_xy = np.asarray(position[:2], dtype=float) - self._odom_origin_xy

        clock = Clock()
        clock.clock.sec = sec
        clock.clock.nanosec = nanosec
        self._clock_publisher.publish(clock)

        odom = Odometry()
        odom.header.stamp = clock.clock
        odom.header.frame_id = "odom"
        odom.child_frame_id = "base_footprint"
        # Odom is local to the spawn pose, matching Gazebo and the convention
        # expected by saved-map localization.
        odom.pose.pose.position.x = float(odom_xy[0])
        odom.pose.pose.position.y = float(odom_xy[1])
        odom.pose.pose.position.z = 0.0
        odom.pose.pose.orientation.w = float(orientation_wxyz[0])
        odom.pose.pose.orientation.x = float(orientation_wxyz[1])
        odom.pose.pose.orientation.y = float(orientation_wxyz[2])
        odom.pose.pose.orientation.z = float(orientation_wxyz[3])
        odom.twist.twist.linear.x = linear_x
        odom.twist.twist.angular.z = angular_z
        self._odom.publish(odom)

        joint_state = JointState()
        joint_state.header.stamp = clock.clock
        joint_state.name = JOINT_STATE_NAMES
        joint_state.position = [float(value) for value in joint_positions]
        self._joint_states.publish(joint_state)

        transform = TransformStamped()
        transform.header = odom.header
        transform.child_frame_id = odom.child_frame_id
        transform.transform.translation.x = odom.pose.pose.position.x
        transform.transform.translation.y = odom.pose.pose.position.y
        transform.transform.translation.z = odom.pose.pose.position.z
        transform.transform.rotation = odom.pose.pose.orientation
        self._tf.publish(TFMessage(transforms=[transform]))


def main() -> None:
    stop_requested = False

    def request_stop(_signum, _frame) -> None:
        nonlocal stop_requested
        stop_requested = True

    signal.signal(signal.SIGINT, request_stop)
    signal.signal(signal.SIGTERM, request_stop)

    temporary_dir = tempfile.TemporaryDirectory(prefix="patrol_robot_isaac_")
    ros_node = None
    try:
        app_utils.enable_extension("isaacsim.ros2.bridge")
        app_utils.enable_extension("isaacsim.sensors.rtx")
        app_utils.enable_extension("isaacsim.sensors.rtx.nodes")
        app_utils.update_app(steps=2)

        work_dir = Path(temporary_dir.name)
        robot_usd = _import_robot(ARGS.urdf_path, work_dir)
        robot = _build_scene(robot_usd)
        controller = AckermannController(
            wheel_base=WHEEL_BASE,
            track_width=TRACK_WIDTH,
            front_wheel_radius=WHEEL_RADIUS,
            back_wheel_radius=WHEEL_RADIUS,
            max_wheel_velocity=MAX_LINEAR_SPEED / WHEEL_RADIUS,
            max_wheel_rotation_angle=MAX_STEERING_ANGLE,
            max_acceleration=2.0,
            max_steering_angle_velocity=math.radians(25.0),
        )

        # Give the four cylindrical wheel contacts additional velocity-solver
        # iterations. The imported articulation root does not carry the PhysX
        # tuning schema by default, so apply it before authoring the setting.
        PhysxSchema.PhysxArticulationAPI.Apply(robot.prims[0])
        robot.set_solver_iteration_counts([32], [4])

        SimulationManager.setup_simulation(dt=PHYSICS_DT, device="cpu")
        physics_scene = SimulationManager.get_physics_scenes()[0]
        physics_scene.set_enabled_gpu_dynamics(False)
        app_utils.play()
        # Initialize the articulation tensor view before setting per-DOF
        # limits.  Unlike repeatedly teleporting the root body, the zero rear
        # wheel target then acts as a physical parking brake.
        app_utils.update_app(steps=2)
        steering_dof_indices = (
            robot.get_dof_indices(STEERING_DOF_NAMES).numpy().tolist()
        )
        front_wheel_dof_indices = (
            robot.get_dof_indices(FRONT_WHEEL_DOF_NAMES).numpy().tolist()
        )
        rear_wheel_dof_indices = (
            robot.get_dof_indices(REAR_WHEEL_DOF_NAMES).numpy().tolist()
        )
        joint_state_dof_indices = (
            robot.get_dof_indices(JOINT_STATE_NAMES).numpy().tolist()
        )
        robot.set_dof_max_efforts(
            np.full(2, STEERING_MAX_EFFORT, dtype=np.float32),
            dof_indices=steering_dof_indices,
        )
        robot.set_dof_max_velocities(
            np.full(2, math.radians(25.0), dtype=np.float32),
            dof_indices=steering_dof_indices,
        )
        robot.set_dof_max_efforts(
            np.full(2, REAR_WHEEL_MAX_EFFORT, dtype=np.float32),
            dof_indices=rear_wheel_dof_indices,
        )
        # Author gains through the live PhysX tensor view. Angular gains stored
        # in USD use degree-based units, which otherwise makes the rear motor
        # roughly 57 times softer than the SI value configured above.
        robot.set_dof_gains(
            stiffnesses=np.full(2, STEERING_DRIVE_STIFFNESS, dtype=np.float32),
            dampings=np.full(2, STEERING_DRIVE_DAMPING, dtype=np.float32),
            dof_indices=steering_dof_indices,
        )
        robot.set_dof_gains(
            stiffnesses=np.zeros(2, dtype=np.float32),
            dampings=np.zeros(2, dtype=np.float32),
            dof_indices=front_wheel_dof_indices,
        )
        robot.set_dof_gains(
            stiffnesses=np.zeros(2, dtype=np.float32),
            dampings=np.full(2, REAR_WHEEL_DRIVE_DAMPING, dtype=np.float32),
            dof_indices=rear_wheel_dof_indices,
        )
        robot.set_dof_max_velocities(
            np.full(2, MAX_LINEAR_SPEED / WHEEL_RADIUS, dtype=np.float32),
            dof_indices=rear_wheel_dof_indices,
        )
        robot.set_dof_position_targets(
            np.zeros(2, dtype=np.float32), dof_indices=steering_dof_indices
        )
        robot.apply_wheel_actions(np.zeros(2, dtype=np.float32))

        # Establish the four ground contacts, then discard the one-time impact
        # impulse from spawning the articulation.  This is an initialization
        # reset only; no root pose or velocity is overridden in the run loop.
        app_utils.update_app(steps=30)
        robot.set_velocities(
            np.zeros((1, 3), dtype=np.float32),
            np.zeros((1, 3), dtype=np.float32),
        )
        robot.set_dof_velocities(
            np.zeros(len(JOINT_STATE_NAMES), dtype=np.float32),
            dof_indices=joint_state_dof_indices,
        )
        app_utils.update_app(steps=150)
        settled_positions, _ = robot.get_world_poses()
        settled_linear, settled_angular = robot.get_velocities()
        settled_dof_velocities = robot.get_dof_velocities(
            dof_indices=joint_state_dof_indices
        )
        print(
            "PATROL_ISAAC_SETTLED "
            f"z={settled_positions.numpy()[0][2]:.5f} "
            f"linear_speed={np.linalg.norm(settled_linear.numpy()[0]):.6f} "
            f"angular_speed={np.linalg.norm(settled_angular.numpy()[0]):.6f} "
            "max_joint_speed="
            f"{np.max(np.abs(settled_dof_velocities.numpy())):.6f}",
            flush=True,
        )
        print(
            "PATROL_ISAAC_SETTLED_JOINTS "
            + " ".join(
                f"{name}={velocity:.6f}"
                for name, velocity in zip(
                    JOINT_STATE_NAMES,
                    settled_dof_velocities.numpy()[0],
                    strict=True,
                )
            ),
            flush=True,
        )
        if ARGS.start_paused:
            app_utils.pause()

        rclpy.init(signal_handler_options=SignalHandlerOptions.NO)
        ros_node = IsaacRosInterface()
        simulation_time = 0.0
        wall_start = time.monotonic()
        publish_every = 3
        step = 0
        last_steering_targets: np.ndarray | None = None
        last_wheel_targets: np.ndarray | None = None
        print(
            "PATROL_ISAAC_READY "
            f"cmd_vel={ARGS.cmd_vel_topic} odom={ARGS.odom_topic} "
            "lidar=/livox/lidar",
            flush=True,
        )

        while not stop_requested and (not ARGS.gui or SIMULATION_APP.is_running()):
            SIMULATION_APP.update()
            # Pressing the GUI Stop button invalidates the articulation's
            # physics tensor view. Pause is an inspection state and must keep
            # the application alive without advancing simulated time.
            if app_utils.is_stopped():
                break
            if app_utils.is_paused():
                rclpy.spin_once(ros_node, timeout_sec=0.0)
                ros_node.command_timeout_brake()
                if ARGS.realtime_factor > 0.0:
                    wall_start = (
                        time.monotonic()
                        - simulation_time / ARGS.realtime_factor
                    )
                time.sleep(0.05)
                continue
            rclpy.spin_once(ros_node, timeout_sec=0.0)
            requested_linear_x, requested_angular_z = ros_node.command(
                simulation_time
            )
            linear_x, steering_angle, angular_z = _bicycle_command(
                requested_linear_x, requested_angular_z
            )
            steering_positions, wheel_velocities = controller.forward(
                [steering_angle, math.radians(25.0), linear_x, 2.0, PHYSICS_DT]
            )
            steering_targets = np.asarray(steering_positions, dtype=np.float32)
            wheel_targets = np.asarray(wheel_velocities[2:], dtype=np.float32)
            # Re-authoring identical drive targets every physics tick wakes the
            # articulation and prevents PhysX from settling at rest.  Targets
            # persist in the drives, so only update them when they change.
            moving = abs(linear_x) >= 1.0e-4
            if (
                moving
                or last_steering_targets is None
                or not np.allclose(
                    steering_targets, last_steering_targets, atol=1.0e-5
                )
            ):
                robot.set_dof_position_targets(
                    steering_targets,
                    dof_indices=steering_dof_indices,
                )
                last_steering_targets = steering_targets.copy()
            if (
                moving
                or last_wheel_targets is None
                or not np.allclose(
                    wheel_targets, last_wheel_targets, atol=1.0e-5
                )
            ):
                robot.apply_wheel_actions(wheel_targets)
                last_wheel_targets = wheel_targets.copy()

            if step % publish_every == 0:
                positions, orientations = robot.get_world_poses()
                linear_velocities, angular_velocities = robot.get_velocities()
                joint_positions = robot.get_dof_positions(
                    dof_indices=joint_state_dof_indices
                )
                orientation = orientations.numpy()[0]
                yaw = math.atan2(
                    2.0
                    * (
                        orientation[0] * orientation[3]
                        + orientation[1] * orientation[2]
                    ),
                    1.0
                    - 2.0
                    * (
                        orientation[2] * orientation[2]
                        + orientation[3] * orientation[3]
                    ),
                )
                world_linear = linear_velocities.numpy()[0]
                actual_linear_x = float(
                    math.cos(yaw) * world_linear[0]
                    + math.sin(yaw) * world_linear[1]
                )
                actual_angular_z = float(angular_velocities.numpy()[0][2])
                ros_node.publish_state(
                    simulation_time,
                    positions.numpy()[0],
                    orientation,
                    joint_positions.numpy().reshape(-1),
                    actual_linear_x,
                    actual_angular_z,
                )
                if step % 6 == 0:
                    ros_node.publish_lidar(
                        simulation_time,
                        positions.numpy()[0],
                        orientation,
                    )

            simulation_time += PHYSICS_DT
            step += 1
            if ARGS.realtime_factor > 0.0:
                wall_deadline = wall_start + simulation_time / ARGS.realtime_factor
                wall_delay = wall_deadline - time.monotonic()
                if wall_delay > 0.0:
                    time.sleep(wall_delay)
            if ARGS.test_seconds > 0.0 and simulation_time >= ARGS.test_seconds:
                break

        # The physics tensor view is invalid whenever the timeline was stopped
        # from the GUI, so avoid articulation reads and writes in that state.
        timeline_stopped = not robot.is_physics_tensor_entity_valid()
        if not timeline_stopped:
            robot.apply_wheel_actions(np.zeros(2, dtype=np.float32))
            robot.set_dof_position_targets(
                np.zeros(2, dtype=np.float32),
                dof_indices=steering_dof_indices,
            )
        if timeline_stopped:
            print("PATROL_ISAAC_FINAL timeline stopped by user", flush=True)
        else:
            positions, _ = robot.get_world_poses()
            final_position = positions.numpy()[0]
            print(
                "PATROL_ISAAC_FINAL "
                f"x={final_position[0]:.3f} y={final_position[1]:.3f} "
                f"z={final_position[2]:.3f}",
                flush=True,
            )
    except BaseException:
        print("PATROL_ISAAC_ERROR", flush=True)
        traceback.print_exc()
        raise
    finally:
        if ros_node is not None:
            ros_node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()
        app_utils.stop()
        temporary_dir.cleanup()
        SIMULATION_APP.close()


if __name__ == "__main__":
    main()
